"""Home page and interface strings for additional languages. Native reader review is required before publication."""

LANGS = [
    {"code": "en", "name": "English", "dir": "ltr", "path": "/"},
    {"code": "ur", "name": "اردو", "dir": "rtl", "path": "/ur/"},
    {"code": "ar", "name": "العربية", "dir": "rtl", "path": "/ar/"},
    {"code": "hi", "name": "हिन्दी", "dir": "ltr", "path": "/hi/"},
    {"code": "es", "name": "Español", "dir": "ltr", "path": "/es/"},
    {"code": "fr", "name": "Français", "dir": "ltr", "path": "/fr/"},
]

UI = {
    "ar": {
        "menu": "كل الأدوات", "skip": "انتقل إلى المحتوى", "about": "من نحن", "privacy": "الخصوصية",
        "contact": "اتصل بنا", "methodology": "المنهجية", "editorial": "سياسة التحرير",
        "tag": "© CalculatesAll. أدوات مجانية تعمل في متصفحك.",
        "faq": "أسئلة شائعة", "more": "المزيد في",
        "h1": "حاسبات إلكترونية مجانية وأدوات مفيدة",
        "title": "CalculatesAll | حاسبات وأدوات مجانية عبر الإنترنت",
        "desc": "حاسبات مجانية للزكاة ومؤشر كتلة الجسم والربح والخسارة والعمر والخصم وتحويل الوحدات والتسبيح والساعة الإيقافية.",
        "lead": "تضم CalculatesAll حاسبات للمال والصحة والتاريخ والوحدات والاستخدام اليومي. تعمل كل أداة في متصفحك، ولا تُرسل بياناتك المُدخلة إلى خادمنا.",
        "heading": "ماذا يمكنك أن تفعل في CalculatesAll",
        "paragraphs": [
            "تجمع CalculatesAll أدوات يستخدمها الناس كل أسبوع. تساعد حسابات الزكاة والربح في القرارات المالية، ويعطي مؤشر كتلة الجسم رقماً للفحص الأولي لدى البالغين، وتتولى أدوات العمر والخصم والوحدات الحسابات اليومية.",
            "يعرض كل أداة صفحة تشرح معادلتها ومثالاً محلولاً وحدودها، لتتمكن من التحقق من النتيجة بنفسك ومعرفة متى تحتاج إلى مختص.",
        ],
        "faq_items": [
            ("هل الحاسبات مجانية؟", "نعم. جميع الأدوات في CalculatesAll مجانية."),
            ("هل تحفظون الأرقام التي أدخلها؟", "لا. تعمل الحسابات في متصفحك، ويحفظ عداد التسبيح عدده على جهازك فقط."),
        ],
        "cats": {"money": "المال والأعمال", "health": "الصحة", "time": "التاريخ والوقت", "math": "الرياضيات والتحويل", "worship": "العبادة والاستخدام اليومي"},
        "cat_desc": {
            "money": "حاسبات الزكاة والربح والخسارة والخصم للقرارات المالية اليومية.",
            "health": "حساب مؤشر كتلة الجسم للبالغين مع الفئات التي حددتها منظمة الصحة العالمية.",
            "time": "حساب العمر بالسنوات والأشهر والأيام، وساعة إيقاف في المتصفح.",
            "math": "حساب حسابي عادي وتحويل الوزن والطول ودرجة الحرارة.",
            "worship": "عداد تسبيح يحفظ العدد على هذا الجهاز فقط.",
        },
    },
    "hi": {
        "menu": "सभी टूल", "skip": "मुख्य सामग्री पर जाएँ", "about": "हमारे बारे में", "privacy": "गोपनीयता",
        "contact": "संपर्क", "methodology": "गणना का तरीका", "editorial": "संपादकीय नीति",
        "tag": "© CalculatesAll. आपके ब्राउज़र में चलने वाले मुफ़्त टूल।",
        "faq": "अक्सर पूछे जाने वाले प्रश्न", "more": "इसी श्रेणी में और",
        "h1": "मुफ़्त ऑनलाइन कैलकुलेटर और उपयोगी टूल",
        "title": "CalculatesAll | मुफ़्त ऑनलाइन कैलकुलेटर और टूल",
        "desc": "ज़कात, BMI, लाभ और हानि, उम्र, छूट, इकाई परिवर्तन, मानक कैलकुलेटर, तसबीह काउंटर और स्टॉपवॉच के मुफ़्त टूल।",
        "lead": "CalculatesAll पर पैसे, स्वास्थ्य, तारीख, इकाइयों और रोज़मर्रा के कैलकुलेटर हैं। हर टूल आपके ब्राउज़र में चलता है और आपके दर्ज किए गए आंकड़े हमारे सर्वर पर नहीं भेजे जाते।",
        "heading": "CalculatesAll पर आप क्या कर सकते हैं",
        "paragraphs": [
            "CalculatesAll में वे टूल हैं जो लोग हर हफ़्ते इस्तेमाल करते हैं। ज़कात और लाभ की गणना पैसों के फ़ैसलों में मदद करती है। BMI वयस्कों के लिए एक प्रारंभिक जाँच का आंकड़ा देता है। उम्र, छूट और इकाई के टूल रोज़ के हिसाब संभालते हैं।",
            "हर टूल के पेज पर उसका सूत्र, एक हल किया हुआ उदाहरण और उसकी सीमाएँ लिखी हैं, ताकि आप परिणाम खुद जाँच सकें और जान सकें कि कब किसी विशेषज्ञ से पूछना ज़रूरी है।",
        ],
        "faq_items": [
            ("क्या ये कैलकुलेटर मुफ़्त हैं?", "हाँ। CalculatesAll के सभी टूल मुफ़्त हैं।"),
            ("क्या आपके दर्ज किए गए आंकड़े सेव होते हैं?", "नहीं। हिसाब आपके ब्राउज़र में होता है। तसबीह काउंटर आपकी गिनती केवल आपके डिवाइस पर रखता है।"),
        ],
        "cats": {"money": "पैसा और व्यापार", "health": "स्वास्थ्य", "time": "तारीख और समय", "math": "गणित और परिवर्तन", "worship": "इबादत और रोज़मर्रा"},
        "cat_desc": {
            "money": "ज़कात, लाभ, हानि और छूट के कैलकुलेटर रोज़मर्रा के पैसों के फ़ैसलों के लिए।",
            "health": "वयस्कों के लिए BMI, विश्व स्वास्थ्य संगठन की श्रेणियों के साथ।",
            "time": "उम्र को वर्ष, महीनों और दिनों में निकालें, और ब्राउज़र स्टॉपवॉच।",
            "math": "सामान्य गणित और वज़न, लंबाई और तापमान का परिवर्तन।",
            "worship": "तसबीह काउंटर जो गिनती केवल इसी डिवाइस पर रखता है।",
        },
    },
    "es": {
        "menu": "Todas las herramientas", "skip": "Ir al contenido", "about": "Acerca de", "privacy": "Privacidad",
        "contact": "Contacto", "methodology": "Metodología", "editorial": "Política editorial",
        "tag": "© CalculatesAll. Herramientas gratuitas que funcionan en tu navegador.",
        "faq": "Preguntas frecuentes", "more": "Más en",
        "h1": "Calculadoras online gratuitas y herramientas útiles",
        "title": "CalculatesAll | Calculadoras y herramientas online gratuitas",
        "desc": "Calculadoras gratuitas de Zakat, IMC, pérdidas y ganancias, edad, descuentos, conversión de unidades, calculadora estándar, contador de tasbih y cronómetro.",
        "lead": "CalculatesAll reúne calculadoras de dinero, salud, fechas, unidades y uso diario. Cada herramienta funciona en tu navegador y tus datos no se envían a nuestro servidor.",
        "heading": "Qué puedes hacer en CalculatesAll",
        "paragraphs": [
            "CalculatesAll reúne herramientas que la gente usa cada semana. Los cálculos de Zakat y de ganancias ayudan a tomar decisiones de dinero. El IMC da una cifra de cribado para adultos. Las herramientas de edad, descuento y unidades resuelven operaciones diarias.",
            "Cada página de herramienta muestra su fórmula, un ejemplo resuelto y sus límites, para que puedas comprobar el resultado tú mismo y saber cuándo consultar a un profesional.",
        ],
        "faq_items": [
            ("¿Las calculadoras son gratuitas?", "Sí. Todas las herramientas de CalculatesAll son gratuitas."),
            ("¿Guardan los números que introduzco?", "No. Los cálculos se hacen en tu navegador. El contador de tasbih guarda su cuenta solo en tu dispositivo."),
        ],
        "cats": {"money": "Dinero y negocios", "health": "Salud", "time": "Fecha y hora", "math": "Matemáticas y conversiones", "worship": "Devoción y uso diario"},
        "cat_desc": {
            "money": "Calculadoras de Zakat, ganancias, pérdidas y descuentos para decisiones de dinero del día a día.",
            "health": "Cálculo del IMC para adultos con las categorías de la Organización Mundial de la Salud.",
            "time": "Calcula la edad en años, meses y días, y un cronómetro en el navegador.",
            "math": "Operaciones aritméticas y conversión de peso, longitud y temperatura.",
            "worship": "Contador de tasbih que guarda la cuenta solo en este dispositivo.",
        },
    },
    "fr": {
        "menu": "Tous les outils", "skip": "Aller au contenu", "about": "À propos", "privacy": "Confidentialité",
        "contact": "Contact", "methodology": "Méthodologie", "editorial": "Politique éditoriale",
        "tag": "© CalculatesAll. Outils gratuits qui fonctionnent dans votre navigateur.",
        "faq": "Questions fréquentes", "more": "Plus dans",
        "h1": "Calculatrices en ligne gratuites et outils utiles",
        "title": "CalculatesAll | Calculatrices et outils en ligne gratuits",
        "desc": "Calculatrices gratuites : Zakat, IMC, bénéfice et perte, âge, remise, conversion d'unités, calculatrice standard, compteur de tasbih et chronomètre.",
        "lead": "CalculatesAll réunit des calculatrices pour l'argent, la santé, les dates, les unités et l'usage quotidien. Chaque outil fonctionne dans votre navigateur, et vos données ne sont pas envoyées à notre serveur.",
        "heading": "Ce que vous pouvez faire sur CalculatesAll",
        "paragraphs": [
            "CalculatesAll réunit des outils que les gens utilisent chaque semaine. Les calculs de Zakat et de bénéfice aident à prendre des décisions financières. L'IMC donne un indicateur de dépistage pour les adultes. Les outils d'âge, de remise et d'unités gèrent les calculs courants.",
            "Chaque page d'outil présente sa formule, un exemple résolu et ses limites, afin que vous puissiez vérifier le résultat vous-même et savoir quand consulter un professionnel.",
        ],
        "faq_items": [
            ("Les calculatrices sont-elles gratuites ?", "Oui. Tous les outils de CalculatesAll sont gratuits."),
            ("Conservez-vous les nombres que je saisis ?", "Non. Les calculs se font dans votre navigateur. Le compteur de tasbih ne garde son total que sur votre appareil."),
        ],
        "cats": {"money": "Argent et affaires", "health": "Santé", "time": "Date et heure", "math": "Maths et conversions", "worship": "Dévotion et usage quotidien"},
        "cat_desc": {
            "money": "Calculatrices de Zakat, de bénéfice, de perte et de remise pour les décisions financières courantes.",
            "health": "Calcul de l'IMC pour adultes, avec les catégories de l'Organisation mondiale de la santé.",
            "time": "Calcul de l'âge en années, mois et jours, et chronomètre dans le navigateur.",
            "math": "Calcul arithmétique et conversion de poids, de longueur et de température.",
            "worship": "Compteur de tasbih qui garde le total uniquement sur cet appareil.",
        },
    },
}
